id: A1D54EE3C
title: Daily Practice of Vajrakīla
type: translation
pechas:
- IBB8C8878
- I4C318989
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:29:53.425392
  last_modified_at: 2023-01-04 11:29:53.425397
  collections:
  - Apang Tertön Series
  - Works of Tibetan Masters
alignment_to_base:
  IBB8C8878/18B3: '6080'
  I4C318989/E229: '6080'
